# Notebook 2: Data Cleaning & Feature Engineering

## Objective

The goal of this notebook is to prepare the supply chain dataset for machine learning and optimization.

Tasks covered:
- Remove unnecessary columns
- Handle missing values
- Remove duplicates
- Convert data types
- Engineer new features
- Encode categorical variables
- Save the cleaned dataset

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

In [2]:


df = pd.read_csv(
    "C:/Users/USER/OneDrive/Desktop/VSCode/c++/SupplyPrescript/data/Raw/SupplyChain/DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

In [3]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
data=df.copy()

In [5]:
print("Duplicate rows:", data.duplicated().sum())

data = data.drop_duplicates()

Duplicate rows: 0

In [6]:
data.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

In [7]:
columns_to_drop = [

    "Customer Email",
    "Customer Password",
    "Customer Fname",
    "Customer Lname",
    "Customer Street",
    "Customer Zipcode",

    "Product Description",
    "Product Image",

    "Latitude",
    "Longitude",

    "Order Zipcode",

    "Order Customer Id",
    "Customer Id",

    "Category Id",
    "Department Id",

    "Product Card Id",
    "Product Category Id",

    "Order Item Cardprod Id",
    "Order Item Id",

    "Order Id"

]

data.drop(columns=columns_to_drop, inplace=True)

In [8]:
data.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Segment', 'Customer State',
       'Department Name', 'Market', 'Order City', 'Order Country',
       'order date (DateOrders)', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

In [9]:
data["order date (DateOrders)"] = pd.to_datetime(
    data["order date (DateOrders)"]
)
data["shipping date (DateOrders)"] = pd.to_datetime(
    data["shipping date (DateOrders)"]
)

In [10]:
data["Lead_Time"] = (
    data["shipping date (DateOrders)"] -
    data["order date (DateOrders)"]
).dt.days

In [11]:
data["Order_Month"] = data["order date (DateOrders)"].dt.month

In [12]:
data["Order_Year"] = data["order date (DateOrders)"].dt.year

In [13]:
data["Order_Weekday"] = data["order date (DateOrders)"].dt.day_name()

In [14]:
data["Profit_Margin"] = (
    data["Benefit per order"] /
    data["Sales"]
)

In [15]:
data["High_Value_Order"] = (
    data["Sales"] >
    data["Sales"].median()
).astype(int)

In [16]:
data.drop(
    columns=[
        "order date (DateOrders)",
        "shipping date (DateOrders)"
    ],
    inplace=True
)

In [17]:
numeric = data.select_dtypes(include=np.number).columns

for col in numeric:
    data[col].fillna(data[col].median(), inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\987750347.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].median(), inplace=True)

In [18]:
categorical = data.select_dtypes(include="object").columns

for col in categorical:
    data[col].fillna(data[col].mode()[0], inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_23328\1959815658.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = data.select_dtypes(include="object").columns
C:\Users\USER\AppData\Local\Temp\ipykernel_23328\1959815658.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[col].fillna(data[col].mode()[0], inplace=True)

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 37 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Name                  180519 non-null  str
 8   Customer City                  180519 non-null  str
 9   Customer Country               180519 non-null  str
 10  Customer Segment               180519 non-null  str
 11  Customer State                 180519 non-null  str
 12  Department Name                180519 non-null  str
 13  Market                         180519 non-null  str
 14  Order City                     180519 non-null  str
 15  Order Country                  180519 non-null  str
 16  Order Item Discount            180519 non-null  float64
 17  Order Item Discount Rate       180519 non-null  float64
 18  Order Item Product Price       180519 non-null  float64
 19  Order Item Profit Ratio        180519 non-null  float64
 20  Order Item Quantity            180519 non-null  int64
 21  Sales                          180519 non-null  float64
 22  Order Item Total               180519 non-null  float64
 23  Order Profit Per Order         180519 non-null  float64
 24  Order Region                   180519 non-null  str
 25  Order State                    180519 non-null  str
 26  Order Status                   180519 non-null  str
 27  Product Name                   180519 non-null  str
 28  Product Price                  180519 non-null  float64
 29  Product Status                 180519 non-null  int64
 30  Shipping Mode                  180519 non-null  str
 31  Lead_Time                      180519 non-null  int64
 32  Order_Month                    180519 non-null  int32
 33  Order_Year                     180519 non-null  int32
 34  Order_Weekday                  180519 non-null  str
 35  Profit_Margin                  180519 non-null  float64
 36  High_Value_Order               180519 non-null  int64
dtypes: float64(11), int32(2), int64(7), str(17)
memory usage: 49.6 MB

In [20]:
data.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,...,Product Name,Product Price,Product Status,Shipping Mode,Lead_Time,Order_Month,Order_Year,Order_Weekday,Profit_Margin,High_Value_Order
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,Smart watch,327.75,0,Standard Class,3,1,2018,Wednesday,0.278413,1
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,...,Smart watch,327.75,0,Standard Class,5,1,2018,Saturday,-0.760000,1
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,...,Smart watch,327.75,0,Standard Class,4,1,2018,Saturday,-0.756003,1
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,...,Smart watch,327.75,0,Standard Class,3,1,2018,Saturday,0.069748,1
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,Smart watch,327.75,0,Standard Class,2,1,2018,Saturday,0.409489,1

In [21]:
data.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Price,Product Status,Lead_Time,Order_Month,Order_Year,Profit_Margin,High_Value_Order
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.0,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107609,0.548291,20.664741,0.101668,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,141.232550,0.0,3.471856,6.235449,2015.971150,0.108326,0.487699
std,1.623722,1.374449,104.433526,120.043670,0.497664,21.800901,0.070415,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,139.732492,0.0,1.670471,3.403571,0.829429,0.420594,0.499850
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,0.000000,0.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,9.990000,0.0,0.000000,1.000000,2015.000000,-2.750000,0.000000
25%,2.000000,2.000000,7.000000,104.379997,0.000000,5.400000,0.040000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,50.000000,0.0,2.000000,3.000000,2015.000000,0.062240,0.000000
50%,3.000000,4.000000,31.520000,163.990005,1.000000,14.000000,0.100000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,59.990002,0.0,3.000000,6.000000,2016.000000,0.242512,0.000000
75%,5.000000,4.000000,64.800003,247.399994,1.000000,29.990000,0.160000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,199.990005,0.0,5.000000,9.000000,2017.000000,0.336014,1.000000
max,6.000000,4.000000,911.799988,1939.989990,1.000000,500.000000,0.250000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,1999.989990,0.0,6.000000,12.000000,2018.000000,0.500443,1.000000

In [22]:
data.isnull().sum().sort_values(ascending=False)

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Segment                 0
Customer State                   0
Department Name                  0
Market                           0
Order City                       0
Order Country                    0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Product Status                   0
Shipping Mode                    0
Lead_Time                        0
Order_Month                      0
Order_Year                       0
Order_Weekday                    0
Profit_Margin                    0
High_Value_Order                 0
dtype: int64

In [23]:
data.to_csv(
    "../data/processed/clean_supply_chain.csv",
    index=False
)

# Summary

Performed the following preprocessing steps:

- Removed duplicate records
- Removed unnecessary columns
- Converted date columns to datetime
- Created new features:
    - Lead_Time
    - Order_Month
    - Order_Year
    - Order_Weekday
    - Profit_Margin
    - High_Value_Order
- Handled missing values
- Saved the cleaned dataset for machine learning