# Notebook 4: Feature Selection & Model Preparation

## Objective

This notebook prepares the dataset for predictive modeling by:

- Selecting the target variable
- Removing data leakage
- Selecting useful features
- Encoding categorical variables
- Splitting data into training and testing sets
- Scaling numerical features (if needed)
- Saving the prepared datasets for model training

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("../data/processed/clean_supply_chain.csv")

data.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,...,Product Name,Product Price,Product Status,Shipping Mode,Lead_Time,Order_Month,Order_Year,Order_Weekday,Profit_Margin,High_Value_Order
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,Smart watch,327.75,0,Standard Class,3,1,2018,Wednesday,0.278413,1
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,...,Smart watch,327.75,0,Standard Class,5,1,2018,Saturday,-0.760000,1
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,...,Smart watch,327.75,0,Standard Class,4,1,2018,Saturday,-0.756003,1
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,...,Smart watch,327.75,0,Standard Class,3,1,2018,Saturday,0.069748,1
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,Smart watch,327.75,0,Standard Class,2,1,2018,Saturday,0.409489,1

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 37 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Name                  180519 non-null  str
 8   Customer City                  180519 non-null  str
 9   Customer Country               180519 non-null  str
 10  Customer Segment               180519 non-null  str
 11  Customer State                 180519 non-null  str
 12  Department Name                180519 non-null  str
 13  Market                         180519 non-null  str
 14  Order City                     180519 non-null  str
 15  Order Country                  180519 non-null  str
 16  Order Item Discount            180519 non-null  float64
 17  Order Item Discount Rate       180519 non-null  float64
 18  Order Item Product Price       180519 non-null  float64
 19  Order Item Profit Ratio        180519 non-null  float64
 20  Order Item Quantity            180519 non-null  int64
 21  Sales                          180519 non-null  float64
 22  Order Item Total               180519 non-null  float64
 23  Order Profit Per Order         180519 non-null  float64
 24  Order Region                   180519 non-null  str
 25  Order State                    180519 non-null  str
 26  Order Status                   180519 non-null  str
 27  Product Name                   180519 non-null  str
 28  Product Price                  180519 non-null  float64
 29  Product Status                 180519 non-null  int64
 30  Shipping Mode                  180519 non-null  str
 31  Lead_Time                      180519 non-null  int64
 32  Order_Month                    180519 non-null  int64
 33  Order_Year                     180519 non-null  int64
 34  Order_Weekday                  180519 non-null  str
 35  Profit_Margin                  180519 non-null  float64
 36  High_Value_Order               180519 non-null  int64
dtypes: float64(11), int64(9), str(17)
memory usage: 51.0 MB

In [4]:
data.shape

(180519, 37)

In [5]:

target = "Late_delivery_risk"

In [6]:
data[target].value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [7]:
leakage_columns = [

    "Late_delivery_risk","Delivery Status","Days for shipping (real)","Order Status"                 
]

In [8]:
data = data.drop(columns=leakage_columns)

In [9]:
id_columns = [

    "Category Id",
    "Department Id",
    "Order Id",
    "Order Item Id",
    "Order Item Cardprod Id",
    "Product Card Id",
    "Product Category Id",
    "Customer Id",
    "Order Customer Id"
]

In [10]:
id_columns = [col for col in id_columns if col in data.columns]

data = data.drop(columns=id_columns)

In [11]:
data.columns

Index(['Type', 'Days for shipment (scheduled)', 'Benefit per order',
       'Sales per customer', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Segment', 'Customer State',
       'Department Name', 'Market', 'Order City', 'Order Country',
       'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Product Name',
       'Product Price', 'Product Status', 'Shipping Mode', 'Lead_Time',
       'Order_Month', 'Order_Year', 'Order_Weekday', 'Profit_Margin',
       'High_Value_Order'],
      dtype='str')

In [12]:
categorical = data.select_dtypes(include="object").columns

categorical

C:\Users\USER\AppData\Local\Temp\ipykernel_20916\2065935575.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = data.select_dtypes(include="object").columns

Index(['Type', 'Category Name', 'Customer City', 'Customer Country',
       'Customer Segment', 'Customer State', 'Department Name', 'Market',
       'Order City', 'Order Country', 'Order Region', 'Order State',
       'Product Name', 'Shipping Mode', 'Order_Weekday'],
      dtype='str')

In [13]:
encoder = LabelEncoder()

for col in categorical:
    data[col] = encoder.fit_transform(data[col])

In [14]:
full_data = pd.read_csv("../data/processed/clean_supply_chain.csv")

y = full_data["Late_delivery_risk"]

In [15]:
X = data

In [16]:
print(X.shape)
print(y.shape)

(180519, 33)
(180519,)

In [17]:
y.value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [18]:
y.value_counts(normalize=True)

Late_delivery_risk
1    0.548291
0    0.451709
Name: proportion, dtype: float64

In [19]:
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

In [20]:
print("Training Features :", X_train.shape)

print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)

print("Testing Labels :", y_test.shape)

Training Features : (144415, 33)
Testing Features : (36104, 33)
Training Labels : (144415,)
Testing Labels : (36104,)

In [21]:
X_train.to_csv("../data/processed/X_train.csv", index=False)

X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)

y_test.to_csv("../data/processed/y_test.csv", index=False)

In [22]:
feature_list = pd.DataFrame({

    "Feature": X.columns

})

feature_list

                          Feature
0                            Type
1   Days for shipment (scheduled)
2               Benefit per order
3              Sales per customer
4                   Category Name
5                   Customer City
6                Customer Country
7                Customer Segment
8                  Customer State
9                 Department Name
10                         Market
11                     Order City
12                  Order Country
13            Order Item Discount
14       Order Item Discount Rate
15       Order Item Product Price
16        Order Item Profit Ratio
17            Order Item Quantity
18                          Sales
19               Order Item Total
20         Order Profit Per Order
21                   Order Region
22                    Order State
23                   Product Name
24                  Product Price
25                 Product Status
26                  Shipping Mode
27                      Lead_Time
28                    Order_Month
29                     Order_Year
30                  Order_Weekday
31                  Profit_Margin
32               High_Value_Order

In [23]:
feature_list.to_csv(

    "../data/processed/features.csv",

    index=False

)

# Summary

Completed the following steps:

- Selected target variable
- Removed data leakage columns
- Removed unnecessary identifiers
- Encoded categorical features
- Split the dataset into training and testing sets
- Saved processed datasets for machine learning

The prepared data is now ready for predictive modeling using Random Forest and XGBoost.